name: Check & fix styling

on: [ push ]

jobs:
    analyse:
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v3

            -
                name: Install composer dependencies
                uses: MilesChou/composer-action/8.1@master
                with:
                    args: install

            -
                name: Run code format
                uses: MilesChou/composer-action/8.1@master
                with:
                    args: format

            -
                name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: 'style: apply code style fix'
